# local computer name
name = pop-os

# remote deskflow server ip
host = 192.168.1.20
port = 24800

xkb_key_offset = 0
backend = uinput

# the below did not help with multiple monitors
# width = 6000
# height = 1440

[idle-inhibit]
enable = false

# Enable tls to send the keystrokes encrypted on the network
[tls]
enable = true
tofu = true

[raw-keymap]
# Menu / modifiers / control
111 = 135 #Menu
60 = 37   #Control_L
59 = 64   #Alt_L
50 = 65   #space
58 = 66   #Caps_Lock
56 = 133  #Super_L
57 = 62   #Shift_R

# Escape + number row
54 = 9    #Escape
19 = 10   #1
20 = 11   #2
21 = 12   #3
22 = 13   #4
24 = 14   #5
23 = 15   #6
27 = 16   #7
29 = 17   #8
26 = 18   #9
30 = 19   #0
28 = 20   #minus
25 = 21   #equal
52 = 22   #BackSpace

# Top letter row
49 = 23   #Tab
13 = 24   #q
14 = 25   #w
15 = 26   #e
16 = 27   #r
18 = 28   #t
17 = 29   #y
33 = 30   #u
35 = 31   #i
32 = 32   #o
36 = 33   #p
31 = 35   #bracketright

# Home row
37 = 36   #Return
1 = 38    #a
2 = 39    #s
3 = 40    #d
4 = 41    #f
6 = 42    #g
5 = 43    #h
39 = 44   #j
41 = 45   #k
38 = 46   #l
42 = 47   #semicolon
40 = 48   #apostrophe
51 = 49   #grave

# Bottom letter row / punctuation
43 = 51   #backslash
7 = 52    #z
8 = 53    #x
9 = 54    #c
10 = 55   #v
12 = 56   #b
46 = 57   #n
47 = 58   #m
44 = 59   #comma
48 = 60   #period
45 = 61   #slash

# Function keys
123 = 67  #F1
121 = 68  #F2
100 = 69  #F3
119 = 70  #F4
97 = 71   #F5
98 = 72   #F6
99 = 73   #F7
101 = 74  #F8
102 = 75  #F9
110 = 76  #F10
104 = 95  #F11
112 = 96  #F12

# Keypad / lock / print
68 = 63   #KP_Multiply
108 = 78  #Scroll_Lock
77 = 104  #KP_Enter
76 = 106  #KP_Divide
106 = 107 #Print
114 = 127 #Pause

# Numeric keypad
90 = 79   #KP_7
92 = 80   #KP_8
93 = 81   #KP_9
79 = 82   #KP_Subtract
87 = 83   #KP_4
88 = 84   #KP_5
89 = 85   #KP_6
70 = 86   #KP_Add
84 = 87   #KP_1
85 = 88   #KP_2
86 = 89   #KP_3
83 = 90   #KP_0
66 = 91   #KP_Delete

# Navigation cluster
116 = 110 #Home
127 = 111 #Up
117 = 112 #Prior
124 = 113 #Left
125 = 114 #Right
120 = 115 #End
126 = 116 #Down
122 = 117 #Next
115 = 118 #Insert
118 = 119 #Delete